// Generated by CoffeeScript 1.6.1
var BGCOLOR, DEBUG, FOGCOLOR, FOGLEVEL, FPS, GRAVITY, MEDIALIST, OBJECTNUM;

DEBUG = true;

BGCOLOR = "black";

OBJECTNUM = 256;

GRAVITY = 9.8;

FOGCOLOR = "#aa9966";

FOGLEVEL = 0.0;

FPS = 30;

MEDIALIST = {
  wall: 'media/picture/chara1.png',
  sky: 'media/picture/sky.jpg',
  all: 'media/picture/all.jpg',
  cafepic: 'media/picture/CloudCafe0001.jpg',
  skyvideo: 'media/video/video-1920x960.mp4',
  drone: 'media/model/Drone.dae',
  droid: 'media/model/droid.dae'
};
