// Generated by CoffeeScript 1.6.1
var sample,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

sample = (function(_super) {

  __extends(sample, _super);

  function sample(sprite) {
    this.sprite = sprite;
    sample.__super__.constructor.call(this, this.sprite);
    this.i = 0.0;
    this.org = (Math.sin(this.r / this.rows + this.i) + Math.sin(this.c / this.cols + this.i)) * 16;
    this.lookatpos = -45.0;
  }

  sample.prototype.destructor = function() {
    return sample.__super__.destructor.call(this);
  };

  sample.prototype.behavior = function() {
    sample.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        this.y = (Math.sin(this.r / this.rows + this.i) + Math.sin(this.c / this.cols + this.i)) * 32;
        this.i += 0.1;
        if (this.y === this.org) {
          this.i = 0.0;
        }
        this.z += 4;
        if (this.z > 100) {
          return this.z = -500;
        }
    }
  };

  return sample;

})(_stationary);
