// Generated by CoffeeScript 1.6.1
var sky,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

sky = (function(_super) {

  __extends(sky, _super);

  function sky(initparam) {
    sky.__super__.constructor.call(this, initparam);
  }

  sky.prototype.destructor = function() {
    return sky.__super__.destructor.call(this);
  };

  sky.prototype.behavior = function() {
    var pad;
    sky.__super__.behavior.call(this);
    switch (this._processnumber) {
      case 0:
        pad = ANALOGSTICK[0];
        if ((pad[0][HORIZONTAL] != null)) {
          return CAMERA.position.set(CAMERA.position.x + parseInt(pad[0][HORIZONTAL] * 30), 0, CAMERA.position.z + parseInt(pad[0][VERTICAL] * 30));
        }
    }
  };

  return sky;

})(_stationary);
